#!/usr/bin/python3
"""FreeRADIUS -> Samba ntlm_auth gate with mandatory winbind group membership."""
import os
import re
import subprocess
import sys


def fail(message):
    print(message, file=sys.stderr)
    raise SystemExit(1)


def main():
    required_gid = None
    domain = ''
    username = ''
    forwarded = []
    for argument in sys.argv[1:]:
        if argument.startswith('--require-group-gid='):
            value = argument.split('=', 1)[1]
            if not value.isdigit():
                fail('Invalid required group GID')
            required_gid = value
            continue
        forwarded.append(argument)
        if argument.startswith('--domain='):
            domain = argument.split('=', 1)[1]
        elif argument.startswith('--username='):
            username = argument.split('=', 1)[1]
    username = username.rsplit('\\', 1)[-1].split('@', 1)[0]
    if not required_gid or not re.fullmatch(r'[A-Za-z0-9._+\-]{1,128}', username):
        fail('Invalid group gate parameters')
    if not re.fullmatch(r'[A-Za-z0-9._\-]{1,64}', domain):
        fail('Invalid domain')
    groups = subprocess.run(['/usr/bin/wbinfo', f'--user-groups={domain}\\{username}'],
                            text=True, capture_output=True, timeout=5)
    gids = {line.strip() for line in groups.stdout.splitlines() if line.strip().isdigit()}
    if groups.returncode or required_gid not in gids:
        fail('NT_STATUS_ACCOUNT_RESTRICTION: User is not a member of the required RADIUS group')
    os.execv('/usr/bin/ntlm_auth', ['ntlm_auth', *forwarded])


if __name__ == '__main__':
    main()
