/* global cockpit */
const $=id=>document.getElementById(id);
let view='overview',snapshot={},selectedUser=localStorage.getItem('cockpit-pm2-user')||'',logTimer=null,snapshotTimer=null,requestBusy=false,logTarget='all',logText='',auditItems=[],confirmAction=null;
const labels={overview:'Ülevaade',apps:'Rakendused',logs:'Reaalajalogid',startup:'Autostart',activity:'Tegevuslogi'};

function esc(value){const node=document.createElement('div');node.textContent=value??'';return node.innerHTML}
async function api(action,data={}){const process=cockpit.spawn(['/usr/local/libexec/cockpit-pm2-helper'],{superuser:'require',err:'message'});process.input(JSON.stringify({action,user:selectedUser,...data}));const raw=await process;const result=JSON.parse(raw||'{}');if(result.error)throw Error(result.error);return result}
function toast(message,error=false){const node=$('toast');node.textContent=message;node.className='toast'+(error?' error':'');clearTimeout(node.timer);node.timer=setTimeout(()=>node.classList.add('hidden'),5000)}
function setLoading(active){$('loading').classList.toggle('hidden',!active);$('content').classList.toggle('hidden',active)}
function head(title,description,actions=''){return `<div class="page-head"><div><h2>${esc(title)}</h2><p>${esc(description)}</p></div><div class="page-actions">${actions}</div></div>`}
function pill(text,kind=''){return `<span class="pill ${kind}">${esc(text)}</span>`}
function bytes(value){let amount=Number(value)||0;const units=['B','KB','MB','GB','TB'];let unit=0;while(amount>=1024&&unit<units.length-1){amount/=1024;unit++}return `${amount>=10||unit===0?amount.toFixed(0):amount.toFixed(1)} ${units[unit]}`}
function uptime(started){if(!started)return '—';let seconds=Math.max(0,Math.floor((Date.now()-started)/1000));const days=Math.floor(seconds/86400);seconds%=86400;const hours=Math.floor(seconds/3600);seconds%=3600;const minutes=Math.floor(seconds/60);if(days)return `${days} p ${hours} h`;if(hours)return `${hours} h ${minutes} min`;if(minutes)return `${minutes} min`;return `${seconds} s`}
function dateTime(value){return value?new Intl.DateTimeFormat('et-EE',{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'—'}
function statusPill(status){const map={online:['Online','ok'],stopped:['Peatatud','warn'],errored:['Viga','bad'],launching:['Käivitub','warn'],'one-launch-status':['Käivitub','warn']};const item=map[status]||[status||'Teadmata',''];return pill(item[0],item[1])}

async function load(showLoading=true){stopPolling();if(showLoading)setLoading(true);try{snapshot=await api('status');selectedUser=snapshot.selected_user;localStorage.setItem('cockpit-pm2-user',selectedUser);renderUserPicker();updateHeader();render()}catch(error){$('content').innerHTML=head(labels[view]||'PM2','')+`<div class="card empty"><strong>Andmeid ei saanud laadida</strong>${esc(error.message)}</div>`;$('health').textContent='Kontroll ebaõnnestus';$('health').className='status bad';toast(error.message,true)}finally{if(showLoading)setLoading(false)}}
function renderUserPicker(){const select=$('user-select');select.innerHTML=snapshot.users.map(user=>`<option value="${esc(user.name)}" ${user.name===selectedUser?'selected':''} ${user.installed?'':'disabled'}>${esc(user.display_name)} (${esc(user.name)})${user.installed?'':' · PM2 puudub'}</option>`).join('')}
function updateHeader(){$('health').textContent=snapshot.summary.online===snapshot.summary.total?(snapshot.summary.total?'Kõik töötab':'Protsesse pole'):`${snapshot.summary.online}/${snapshot.summary.total} töötab`;$('health').className='status '+(snapshot.summary.online===snapshot.summary.total?'ok':'bad');$('subtitle').textContent=`PM2 ${snapshot.version||'—'} · ${selectedUser} · ${snapshot.pm2_home}`}
function render(){({overview:renderOverview,apps:renderApps,logs:renderLogs,startup:renderStartup,activity:renderActivity}[view]||renderOverview)();bind();updatePolling()}

function processRows(processes){return processes.map(process=>`<tr><td><div class="app-name"><span class="app-icon">${esc(process.name.slice(0,2).toUpperCase())}</span><div><strong>${esc(process.name)}</strong><small>ID ${process.id} · ${esc(process.namespace)}</small>${process.public_url?`<a class="public-link" href="${esc(process.public_url)}" target="_blank" rel="noopener">↗ ${esc(process.public_url)}</a>`:''}</div></div></td><td>${statusPill(process.status)}</td><td><div class="resource"><strong>${process.cpu.toFixed(1)}%</strong><small>${bytes(process.memory)}</small></div></td><td>${uptime(process.started)}</td><td>${process.restarts}</td><td class="actions">${process.status==='online'?`<button class="button small" data-process="${process.mode==='cluster'?'reload':'restart'}" data-id="${process.id}">${process.mode==='cluster'?'Laadi sujuvalt':'Taaskäivita'}</button><button class="button small" data-process="stop" data-id="${process.id}">Peata</button>`:`<button class="button small primary" data-process="start" data-id="${process.id}">Käivita</button>`}<button class="button small" data-detail="${process.id}">Detailid</button><button class="button small danger" data-delete="${process.id}">Kustuta</button></td></tr>`).join('')}
function processTable(processes){return processes.length?`<div class="table-wrap"><table><thead><tr><th>Rakendus</th><th>Olek</th><th>CPU / mälu</th><th>Tööaeg</th><th>Restarte</th><th></th></tr></thead><tbody>${processRows(processes)}</tbody></table></div>`:`<div class="empty"><strong>PM2 rakendusi pole</strong>Lisa esimene rakendus või taasta salvestatud protsessinimekiri.</div>`}

function renderOverview(){const s=snapshot;$('content').innerHTML=head('PM2 ülevaade',`Kasutaja ${selectedUser} rakenduste tervis ja ressursikasutus`,`<button class="button primary" data-add>+ Lisa rakendus</button>`)+`<div class="metrics"><div class="metric"><span>Rakendusi</span><strong>${s.summary.total}</strong><small>${s.summary.online} töötab</small></div><div class="metric"><span>CPU kokku</span><strong>${s.summary.cpu.toFixed(1)}%</strong><small>PM2 protsessid</small></div><div class="metric"><span>Mälu kokku</span><strong>${bytes(s.summary.memory)}</strong><small>residentmälu</small></div><div class="metric"><span>Autostart</span><strong>${s.startup.enabled?'Sees':'Väljas'}</strong><small>${s.dump.count} salvestatud rakendust</small></div></div>${s.summary.stopped?`<div class="notice warning"><strong>${s.summary.stopped} rakendust ei tööta.</strong> Vaata olekut ja logisid enne taaskäivitamist.</div>`:`<div class="notice success"><strong>${s.summary.total?'Kõik rakendused töötavad.':'PM2 on valmis.'}</strong> ${s.summary.total?'Jõudlusnäidud uuenevad automaatselt.':'Lisa rakendus või taasta varasem nimekiri.'}</div>`}<div class="card"><div class="card-head"><h3>Rakendused</h3><span class="muted">uuendub iga 5 sekundi järel</span></div>${processTable(s.processes)}</div>`}
function renderApps(){$('content').innerHTML=head('Rakendused','Käivita, peata ja halda valitud kasutaja PM2 protsesse',`<button class="button" data-all="restart">Taaskäivita kõik</button><button class="button primary" data-add>+ Lisa rakendus</button>`)+`<div class="card">${processTable(snapshot.processes)}</div>`}
function renderLogs(){const options=[`<option value="all">Kõik rakendused</option>`,...snapshot.processes.map(process=>`<option value="${process.id}" ${String(process.id)===String(logTarget)?'selected':''}>${esc(process.name)} · ID ${process.id}</option>`)].join('');$('content').innerHTML=head('Reaalajalogid','PM2 väljund uueneb automaatselt ja kerib viimase sündmuseni',`<span id="live-state" class="pill ok">● Reaalajas</span><button class="button danger" data-flush>Tühjenda logid</button>`)+`<div class="card"><div class="log-toolbar"><label class="field"><span>Rakendus</span><select id="log-target">${options}</select></label><span class="muted">Viimased 160 rida · uuendus iga 2 sekundi järel</span></div><pre id="log-box" class="log-box">${esc(logText||'Ootan logisündmusi…')}</pre></div>`;scrollLog()}
function renderStartup(){const s=snapshot;$('content').innerHTML=head('Autostart ja protsessinimekiri','Taasta rakendused automaatselt pärast serveri taaskäivitust')+`<div class="startup-layout"><div class="card"><div class="card-head"><h3>Systemd autostart</h3>${pill(s.startup.enabled?'Lubatud':'Keelatud',s.startup.enabled?'ok':'warn')}</div><div class="startup-state ${s.startup.enabled?'':'bad'}"><span class="state-icon">${s.startup.enabled?'✓':'!'}</span><div><strong>${esc(s.startup.unit)}</strong><div class="muted">${s.startup.active?'Teenus töötab praegu':'Teenus ei ole systemd all aktiivne'}</div></div></div><p>Autostart käivitab kasutaja <strong>${esc(selectedUser)}</strong> salvestatud PM2 protsessid pärast võrgu valmimist.</p><div class="button-row"><button class="button ${s.startup.enabled?'danger':'primary'}" data-startup="${s.startup.enabled?'disable':'enable'}">${s.startup.enabled?'Keela autostart':'Luba autostart'}</button></div></div><div class="card"><div class="card-head"><h3>Salvestatud nimekiri</h3>${pill(`${s.dump.count} rakendust`,s.dump.exists?'ok':'warn')}</div><dl class="kv"><dt>Fail</dt><dd class="code">${esc(s.pm2_home)}/dump.pm2</dd><dt>Viimati salvestatud</dt><dd>${dateTime(s.dump.modified)}</dd><dt>Rakendusi</dt><dd>${s.dump.count}</dd></dl><div class="button-row"><button class="button primary" data-operation="save">Salvesta praegune nimekiri</button><button class="button" data-operation="resurrect" ${s.dump.exists?'':'disabled'}>Taasta nimekiri</button></div></div></div><div class="notice warning"><strong>Oluline:</strong> pärast rakenduste lisamist või kustutamist vajuta „Salvesta praegune nimekiri”, et muudatus kehtiks ka pärast serveri restarti.</div>`}
function renderActivity(){const rows=auditItems.slice().reverse().map(item=>`<li><time>${dateTime(item.time)}</time><span>${esc(actionLabel(item.action))}</span><strong>${esc(item.target||'—')}</strong></li>`).join('');$('content').innerHTML=head('Tegevuslogi','Cockpiti PM2 mooduli kaudu tehtud haldustoimingud',`<button class="button" data-audit-refresh>↻ Värskenda</button>`)+`<div class="card">${rows?`<ul class="timeline">${rows}</ul>`:`<div class="empty"><strong>Tegevusi pole</strong>Siin kuvatakse mooduli kaudu tehtud muudatused.</div>`}</div>`}
function actionLabel(action){return ({app_add:'Lisati rakendus',process_start:'Käivitati',process_restart:'Taaskäivitati',process_reload:'Laaditi sujuvalt',process_stop:'Peatati',process_reset:'Nulliti loendurid',process_delete:'Kustutati',save:'Salvestati nimekiri',resurrect:'Taastati nimekiri',startup_enable:'Lubati autostart',startup_disable:'Keelati autostart',flush_logs:'Tühjendati logid'})[action]||action}

function bind(){document.querySelectorAll('[data-add]').forEach(button=>button.onclick=openAdd);document.querySelectorAll('[data-process]').forEach(button=>button.onclick=()=>processAction(button.dataset.process,button.dataset.id,button));document.querySelectorAll('[data-detail]').forEach(button=>button.onclick=()=>openDetail(button.dataset.detail));document.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>confirmDelete(button.dataset.delete));document.querySelectorAll('[data-all]').forEach(button=>button.onclick=()=>allAction(button.dataset.all));const target=$('log-target');if(target)target.onchange=()=>{logTarget=target.value;logText='';refreshLogs()};const flush=document.querySelector('[data-flush]');if(flush)flush.onclick=confirmFlush;document.querySelectorAll('[data-operation]').forEach(button=>button.onclick=()=>operation(button.dataset.operation,button));document.querySelectorAll('[data-startup]').forEach(button=>button.onclick=()=>operation(`startup_${button.dataset.startup}`,button));const audit=document.querySelector('[data-audit-refresh]');if(audit)audit.onclick=loadAudit}
function stopPolling(){if(logTimer)clearInterval(logTimer);if(snapshotTimer)clearInterval(snapshotTimer);logTimer=snapshotTimer=null}
function updatePolling(){stopPolling();if(document.visibilityState!=='visible')return;if(view==='logs'){refreshLogs();logTimer=setInterval(refreshLogs,2000)}else if(view==='overview'||view==='apps'){snapshotTimer=setInterval(refreshSnapshot,5000)}}
async function refreshSnapshot(){if(requestBusy)return;requestBusy=true;try{const fresh=await api('snapshot');snapshot={...snapshot,...fresh,users:snapshot.users};updateHeader();if(view==='overview'||view==='apps')render()}catch(error){$('health').textContent='Ühendus katkes';$('health').className='status bad'}finally{requestBusy=false}}
async function refreshLogs(){if(view!=='logs'||requestBusy)return;requestBusy=true;try{const result=await api('logs',{id:logTarget});logText=result.log||'Logi on tühi.';const box=$('log-box');if(box){box.textContent=logText;const state=$('live-state');state.textContent='● Reaalajas';state.className='pill ok';scrollLog()}}catch(error){const state=$('live-state');if(state){state.textContent='● Ühendus katkes';state.className='pill bad'}}finally{requestBusy=false}}
function scrollLog(){requestAnimationFrame(()=>{const box=$('log-box');if(box)box.scrollTop=box.scrollHeight})}

function switchView(next){view=next;document.querySelectorAll('#nav button').forEach(button=>button.classList.toggle('active',button.dataset.view===view));if(view==='logs')logText='';render();if(view==='activity')loadAudit()}
function routeSlug(value){return String(value||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').slice(0,63)}
function openAdd(){const form=$('app-form');form.reset();form.elements.cwd.value=`${snapshot.users.find(user=>user.name===selectedUser)?.home||`/home/${selectedUser}`}/Projects`;form.elements.instances.value='1';form.elements.autorestart.checked=true;form.elements.public_domain.value=snapshot.public_domain||'';form.elements.public_port.value='3000';form.elements.public_path.dataset.touched='';const syncMode=()=>{form.elements.instances.disabled=form.elements.mode.value!=='cluster';form.elements.instances.closest('.field').classList.toggle('muted',form.elements.instances.disabled)};const syncPublish=()=>{const active=form.elements.publish.checked;$('publish-fields').classList.toggle('hidden',!active);['public_domain','public_path','public_port'].forEach(name=>form.elements[name].required=active)};form.elements.mode.onchange=syncMode;form.elements.publish.onchange=syncPublish;form.elements.name.oninput=()=>{if(!form.elements.public_path.dataset.touched)form.elements.public_path.value='/'+routeSlug(form.elements.name.value)};form.elements.public_path.oninput=()=>form.elements.public_path.dataset.touched='true';syncMode();syncPublish();$('app-dialog').showModal()}
function openDetail(id){const process=snapshot.processes.find(item=>String(item.id)===String(id));if(!process)return;$('detail-title').textContent=process.name;$('detail-content').innerHTML=`<div class="metrics"><div class="metric"><span>Olek</span><strong>${esc(process.status)}</strong></div><div class="metric"><span>PID</span><strong>${process.pid||'—'}</strong></div><div class="metric"><span>CPU</span><strong>${process.cpu.toFixed(1)}%</strong></div><div class="metric"><span>Mälu</span><strong>${bytes(process.memory)}</strong></div></div><dl class="kv"><dt>PM2 ID</dt><dd>${process.id}</dd>${process.public_url?`<dt>Avalik aadress</dt><dd><a href="${esc(process.public_url)}" target="_blank" rel="noopener">${esc(process.public_url)}</a></dd>`:''}<dt>Käivitusfail</dt><dd class="code">${esc(process.script)}</dd><dt>Töökataloog</dt><dd class="code">${esc(process.cwd)}</dd><dt>Interpretaator</dt><dd>${esc(process.interpreter||'Automaatne')}</dd><dt>Režiim</dt><dd>${esc(process.mode)} · ${process.instances} instants(i)</dd><dt>Node.js</dt><dd>${esc(process.node_version||'—')}</dd><dt>Rakenduse versioon</dt><dd>${esc(process.version||'—')}</dd><dt>Käivitatud</dt><dd>${dateTime(process.started)}</dd><dt>Tööaeg</dt><dd>${uptime(process.started)}</dd><dt>Restarte</dt><dd>${process.restarts}</dd><dt>Automaatne restart</dt><dd>${process.autorestart?'Jah':'Ei'}</dd><dt>Failijälgimine</dt><dd>${process.watch?'Sees':'Väljas'}</dd><dt>Mälupiirang</dt><dd>${process.max_memory_restart?bytes(process.max_memory_restart):'Puudub'}</dd></dl><div class="button-row"><button class="button" data-detail-log>Vaata logi</button><button class="button" data-detail-reset>Nulli restardiloendur</button></div>`;$('detail-dialog').showModal();document.querySelector('[data-detail-log]').onclick=()=>{$('detail-dialog').close();logTarget=String(process.id);switchView('logs')};document.querySelector('[data-detail-reset]').onclick=()=>processAction('reset',process.id,document.querySelector('[data-detail-reset]'))}
async function processAction(operationName,id,button){button.disabled=true;try{const result=await api('process_action',{operation:operationName,id});toast(result.message);await load(false)}catch(error){toast(error.message,true)}finally{button.disabled=false}}
async function allAction(operationName){const targets=snapshot.processes.filter(process=>operationName!=='restart'||process.status==='online');if(!targets.length)return toast('Sobivaid protsesse pole.');for(const process of targets){try{await api('process_action',{operation:operationName,id:process.id})}catch(error){toast(`${process.name}: ${error.message}`,true);return}}toast(`${targets.length} rakendust taaskäivitati.`);await load(false)}
async function operation(action,button){button.disabled=true;try{const result=await api(action);toast(result.message);await load(false)}catch(error){toast(error.message,true)}finally{button.disabled=false}}
function confirmDelete(id){const process=snapshot.processes.find(item=>String(item.id)===String(id));if(!process)return;confirmAction={action:'process_delete',data:{id:process.id},expected:process.name};$('confirm-title').textContent='Eemalda PM2 rakendus';$('confirm-text').textContent=`${process.name} peatatakse ja eemaldatakse PM2 protsessinimekirjast. Rakenduse faile ei kustutata.`;$('confirm-prompt').innerHTML=`Sisesta kinnituseks <span class="confirm-copy">${esc(process.name)}</span>`;$('confirm-input').value='';$('confirm-dialog').showModal()}
function confirmFlush(){confirmAction={action:'flush_logs',data:{},expected:'KUSTUTA LOGID'};$('confirm-title').textContent='Tühjenda kõik PM2 logid';$('confirm-text').textContent=`See tühjendab kasutaja ${selectedUser} kõigi PM2 rakenduste olemasolevad väljund- ja vealogid.`;$('confirm-prompt').innerHTML='Sisesta kinnituseks <span class="confirm-copy">KUSTUTA LOGID</span>';$('confirm-input').value='';$('confirm-dialog').showModal()}
async function loadAudit(){try{auditItems=(await api('activity')).items;renderActivity();bind()}catch(error){toast(error.message,true)}}

$('nav').onclick=event=>{const button=event.target.closest('[data-view]');if(button)switchView(button.dataset.view)};
$('refresh').onclick=()=>load();
$('user-select').onchange=()=>{selectedUser=$('user-select').value;localStorage.setItem('cockpit-pm2-user',selectedUser);logTarget='all';logText='';auditItems=[];load()};
document.addEventListener('visibilitychange',updatePolling);
document.querySelectorAll('[data-close-app]').forEach(button=>button.onclick=()=>$('app-dialog').close());
document.querySelectorAll('[data-close-detail]').forEach(button=>button.onclick=()=>$('detail-dialog').close());
document.querySelectorAll('[data-close-confirm]').forEach(button=>button.onclick=()=>$('confirm-dialog').close());
$('app-form').onsubmit=async event=>{event.preventDefault();const button=$('app-submit');const form=event.currentTarget;const data=Object.fromEntries(new FormData(form));data.autorestart=form.elements.autorestart.checked;data.watch=form.elements.watch.checked;data.publish=form.elements.publish.checked;data.strip_prefix=form.elements.strip_prefix.checked;data.public_websocket=form.elements.public_websocket.checked;button.disabled=true;try{const result=await api('app_add',data);$('app-dialog').close();toast(result.message);await load(false)}catch(error){toast(error.message,true)}finally{button.disabled=false}};
$('confirm-form').onsubmit=async event=>{event.preventDefault();if($('confirm-input').value!==confirmAction.expected)return toast('Kinnitustekst ei ühti.',true);const button=$('confirm-submit');button.disabled=true;try{const result=await api(confirmAction.action,{...confirmAction.data,confirm:$('confirm-input').value});$('confirm-dialog').close();toast(result.message);if(confirmAction.action==='flush_logs'){logText='';await refreshLogs()}else await load(false)}catch(error){toast(error.message,true)}finally{button.disabled=false}};
load();
